In [4]:
#Library
import numpy as np
import tensorflow as rf

NGC 5
1. BuatlahTensor di bawahinidenganPython:[[23,50,7,12],
[57,67,99,43],
[75,21,57,12],
[87,26,18,84]]


In [24]:
Array = np.array([[[23,50],[7,12]], [[75,21],[57,12]],[[57,67],[99,43]], [[87,26],[18,84]]])
Array

array([[[23, 50],
        [ 7, 12]],

       [[75, 21],
        [57, 12]],

       [[57, 67],
        [99, 43]],

       [[87, 26],
        [18, 84]]])

2. Lakukan perkalian terhadap matrix berikut: 𝐴=[23,50,19,7,12,109,57,67,98]𝐵=[17,22,19]


In [11]:
A = np.array([
             [23,50,19],
             [7,12,109],
             [57,67,98]
            ])
print(A)

B = np.array([
             [17],
             [22],
             [19]
              ])
print(B)



[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
[[17]
 [22]
 [19]]


In [12]:
#Element Wise
A * B

array([[ 391,  850,  323],
       [ 154,  264, 2398],
       [1083, 1273, 1862]])

In [13]:
#Multification
A @ B

array([[1852],
       [2454],
       [4305]])

In [14]:
#Problem 3 -Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini: 𝐴=[235019712109576798]
A = np.array ([[23,7,57],[50,12,67],[19,109,98]])
A

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [15]:
#Transporse
A.transpose()

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [17]:
#determinant
np.linalg.det(A)

131343.99999999997

In [19]:
#invers
np.linalg.inv(A)

array([[-0.0466485 ,  0.04208034, -0.00163692],
       [-0.02761451,  0.00891552,  0.0099662 ],
       [ 0.03975819, -0.01807467, -0.00056341]])